### ISSUE TITLE
能否根据进程pid进行代理呢?

### ISSUE THREAD

**Issue by 23233** [PinkD/nft-game#1]
如题

**Comment by PinkD** [comment]
https://github.com/PinkD/nft-game/blob/62d2ba2b730b94f030fc81388ecdb3381806e308/netfilter.cpp#L274-L284

在这里加一个直接用 pid 的逻辑就行了，得把这个 pid 从参数传进去。你可以看下怎么改比较好，欢迎提 pr 

另外，如果可以用进程名，为啥还要用 pid 呢

**Comment by 23233** [comment]
是这样的 我使用模拟器 该死的模拟器都是一个名
![OO6${4VA$%AW5V ~7ZMSMQX](https://user-images.githubusercontent.com/12870070/232690856-f279ee79-a622-4091-a209-f0091afb1dd8.png)
所以我才需要使用pid来设置代理 确保每一个模拟器进行到代理

**Comment by 23233** [comment]
我已经在开始调试了 不过这个wireguard有点让我摸不着头脑 
请问我是不是需要在服务器上部署wireguard 并且开放 然后在配置文件中跟服务器配置对接上?
那socket5是怎样体现的呢? 
有任何案例给我参考一下?  @PinkD 
谢谢!

**Comment by PinkD** [comment]
如果没什么技术底子，那我建议你先看看 [netch](https://github.com/netchx/netch) 能不能实现这个功能，至少有界面，可以支持多种协议。但是 netch 需要一个比较完整的 socks5 server 才能有好的 udp 体验。可以在 github 上找两个支持 udp 的 socks5 server
原理上的话，本软件其实就是用 netfilter2 将流量通过 gvisor 重定向到 wireguard 上，然后发送给 wg server ，因此是需要在服务端配置 wg ，然后用本软件去连接的

**Comment by 23233** [comment]
是我代入了 我老是去想到socket5代理去了 实际上本项目 把"进程" network 都重定向给了 wireguard server .
