### ISSUE TITLE
Bind to specified network adapter

### ISSUE THREAD

**Issue by chise0713** [PinkD/nft-game#2]
instead using wireguard-go
这样是可行的吗，假设是可行的，我该如何修改代码来做到我所说的行为

**Comment by PinkD** [comment]
没明白你的需求，这个项目的作用是通过 netfilter 框架将进程的流量通过 wg-go 转发出去。绑定接口是为了实现什么？

**Comment by chise0713** [comment]
在软件没有绑定网卡的选项时，用于指定软件的出站网卡

**Comment by PinkD** [comment]
为什么要指定出站网卡？你举个实际的例子？

**Comment by chise0713** [comment]
抱歉打扰了。
比如说我这个特定的网络环境下，一个网卡有 nat4 v4 地址，另一个是 nat1/open v4，但是正常使用时需要 nat4 这个网卡的 v4 获得正常的流媒体，只有在软件需要 nat1/open （例如跑种子）时指定这个软件的出站网卡为 nat1/open。
我其实也不太能想出指定出站网卡的实际例子，我的想法是使用别的软件创建一个虚拟网卡，例如 sing-box/clash.meta 的 tun，然后使用一些专门的代理协议过墙，而不是使用 wireguard 协议。

**Comment by PinkD** [comment]
> 我的想法是使用别的软件创建一个虚拟网卡，例如 sing-box/clash.meta 的 tun，然后使用一些专门的代理协议过墙，而不是使用 wireguard 协议。

那就要把 wg 的 device 抽象成接口，基于其它的协议实现这些接口，通过配置策略需要使用哪个协议。工作量会很大。这个项目是我没配透明代理之前搞来玩游戏的，现在也不需要了，所以目前我个人最多只会在这个项目上做一些小的 bug fix

你可以考虑 fork 一份修改，或者借鉴一下思路自己实现一个

另外，其实对于玩游戏来说， wg 已经是非常高效率的一个方案了，如果怕丢包也可以在外面套 udp speeder 啥的。如果底层换成 v2ray 或者其它工具，是有可能会让体验变差的

**Comment by chise0713** [comment]
好的，感谢回答
