### ISSUE TITLE
能否编译成dll版本

### ISSUE THREAD

**Issue by mingtianquan** [PinkD/nft-game#3]

**Comment by PinkD** [comment]
编译为 dll 的意义在哪里？让其他程序调用？那为什么不直接修改本项目的源码？

**Comment by mingtianquan** [comment]
对的他编译出来是易语言调用 来添加进程，让进程来代理SOCKS5、Shadowsocks

**Comment by mingtianquan** [comment]
大佬你有没有qq加下你或者你加我83830979

**Comment by PinkD** [comment]
本程序没有 GUI ，只有命令行，由于是独立的程序，也没有计划提供 SDK 
本程序支持通过命令行参数指定需要代理的程序，不支持其他协议，也没有计划支持其他协议，因为本程序直接走 wireguard 协议，可以代理 TCP 和 UDP
你可以尝试阅读 README.md 或者源码来了解该程序的原理

**Comment by PinkD** [comment]
> 对的他编译出来是易语言调用 来添加进程，让进程来代理SOCKS5、Shadowsocks

另外，进程代理 SOCKS5 的说法有问题， SOCKS5 是一种协议，没有被代理的说法。你可以去了解一下什么是代理，什么是 SOCKS5
